version: '2'


services:

  logserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logserver
    ports:
      - "34000:6000"
  logserver1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logserver1
    ports:
      - "34001:6000"
  logserver2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logserver2
    ports:
      - "34002:6000"

  db:
    image: mongo:3.6.1
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    command: mongod

volumes:
  mongodb:
  mongodb_config: